---
# run_task_03.yml
- name: "Tarea 0.3 Bizagi - Inventario"
  hosts: servers_origen
  gather_facts: false

  vars:
    task_config:
      id: "0_3"
      description: "Sincronizacion Scripts Prod → Contingencia"
      name_share: "Cont_Documentos"
      scripts_parth: "D:\\Mis Documentos"
      file_patterns: ["*.bat", "*.ps1"]
      cont_share: "\\\\{{ groups['servers_cont_03'][0] }}\\Cont_Documentos"

  pre_tasks:
    - name: Configurar carpeta compartida en contingencia
      ansible.windows.win_share:
        name: "{{ task_config.name_share }}"
        path: "{{ task_config.scripts_parth }}"
        list: false
        full: "Administrators"
        state: present
        description: Configurar carpeta compartida en contingencia
