---
- name: "Playbook - Target Objetivo"
  hosts: localhost
  gather_facts: false

  vars:
    # variables a nivel playbook
    task_targets: "{{ (task_targets_input | default('') | split('\n')) | select('truthy') | list }}"
    check_type: "{{ test_connection_check_type | default('') }}"

  tasks:
    - name: "Validar si hay targets configurados"
      ansible.builtin.debug:
        msg:
          - "Targets: {{ task_targets | length }} configurados"
          - "Tipo: {{ check_type }}"

    - name: "(INFORMATIVO) - Validar parámetros requeridos"
      ansible.builtin.assert:
        that:
          - task_targets_input is defined
          - task_targets_input | length > 0
          - test_connection_check_type is defined
          - test_connection_check_type | length > 0
        fail_msg: "Parámetros requeridos faltantes o vacíos: task_targets_input y/o test_connection_check_type"
        success_msg: "OK: Todos los parámetros requeridos están definidos y no vacíos"

    - name: "(INFORMATIVO) - Validar formato de IPs"
      ansible.builtin.assert:
        that:
          - task_targets | length > 0
          - task_targets | reject('match', '^([0-9]{1,3}\.){3}[0-9]{1,3}$') | list | length == 0
        fail_msg: "ERROR: Todos los valores en 'Hosts' deben estar deparados por ENTER y/o ser IP validas (Ej: 192.168.20.50)."
        success_msg: "OK: Las IPs descritas tienen un formato válido"

    - name: "(INFORMATIVO) - Validar PUERTOS con numero de 1 a 5 digitos"
      ansible.builtin.assert:
        that:
          - task_ports_input is string
          - task_ports_input | regex_search('^[0-9]{1,5}$')
        fail_msg: "ERROR: El PUERTO deber un numero de 1 a 5 digitos (Ej: 5985)."
        success_msg: "OK: Puerto valido"
      when: check_type in ['telnet', 'ambos']

- name: "Playbook - Prueba Conectividad"
  hosts: all_servers
  gather_facts: false

  vars:
    # variables a nivel playbook
    task_targets: "{{ (task_targets_input | default('')) | split('\n') | list }}"
    task_ports: "{{ (task_ports_input | default('')) | split('\n') | list }}"
    task_id: "{{ custom_task_id | default('Conexion') }}"
    task_description: "Prueba Conectividad Telnet/Ping"

  pre_tasks:
    - name: "Recuperar Facts"
      ansible.builtin.setup:
      ignore_unreachable: true
      register: fact_result
      retries: 3
      delay: 5
      until: not fact_result.unreachable | default(false)

    - name: "Establecer estado de los Facts"
      ansible.builtin.set_fact:
        facts_generated: true
      when: ansible_os_family is defined

    - name: "Crear resultado si es No alcanzable"
      when: facts_generated is not defined
      block:
        - name: "Registrar error de recoleccion de Facts"
          ansible.builtin.set_fact:
            connectivity_result:
              start_time: "{{ ansible_date_time.date | default('N/A') }} - {{ ansible_date_time.time | default('N/A') }}"
              task_id: "{{ task_id }}"
              source_host: "{{ inventory_hostname }}"
              results: ["{{ inventory_hostname }} = UNREACHABLE"]
              status: "unreachable"

  tasks:
    - name: "Ejecutar Tarea - {{ task_description }}"
      ansible.builtin.include_role:
        name: test_connection
      vars:
        test_connection_check_type: "telnet"
        test_connection_target_hosts: "{{ task_targets }}"
        test_connection_ports: "{{ task_ports }}"
        test_connection_task_id: "{{ task_id }}"
        test_connection_task_description: "{{ task_description }}"
        test_connection_show_details: true
      when:
        - facts_generated is defined

    - name: "CLICK: Mostrar resultado"
      ansible.builtin.debug:
        msg:
          - "===================================="
          - "TAREA {{ connectivity_result.task_id }} completada:"
          - "===================================="
          - "Hora: {{ connectivity_result.start_time }}"
          - "Host: {{ connectivity_result.source_host }}"
          - "Status: {{ connectivity_result.status }}"
          - "Results: {{ connectivity_result.results }}"
          - "===================================="
