---
# tasks file for roles/telnet_check
- name: "(FAIL) - Validar parámetros requeridos"
  ansible.builtin.fail:
    msg: "Parámetro requerido faltante: {{ item }}"
  when: vars[item] is not defined or vars[item] | length == 0
  loop:
    - telnet_check_target_hosts
    - telnet_check_check_type

- name: "(FAIL) - Validar puertos para telnet"
  ansible.builtin.fail:
    msg: "Puertos requeridos para check_type telnet"
  when: telnet_check_check_type in ['telnet']
    and (telnet_check_ports is not defined or telnet_check_ports | length == 0)

- name: "Mostrar configuración de la prueba"
  ansible.builtin.debug:
    msg:
      - "===================================="
      - "TAREA {{ telnet_check_task_id }}: {{ telnet_check_task_description }}"
      - "===================================="
      - "Desde: {{ inventory_hostname }}"
      - "Tipo: {{ telnet_check_check_type }}"
      - "Destinos: {{ telnet_check_target_hosts | join(', ') }}"
      - "Puertos: {{ telnet_check_ports | default(['N/A']) | join(', ') }}"
      - "===================================="

- name: Ejecutar Test Windows
  ansible.builtin.include_tasks:
    file: windows.yml
  when: ansible_os_family == 'Windows'

- name: Ejecutar Test Linux
  ansible.builtin.include_tasks:
    file: linux.yml
  when: ansible_os_family in ['RedHat', 'Debian']
