---
# defaults file for roles/file_comparison

# Identificación de la tarea
file_comparison_task_id: "0_3"
file_comparison_task_description: "Validacion de Archivos"

# Patrones de archivos a comparar
file_comparison_file_patterns:
  - "*.bat"
  - "*.ps1"

# Ruta por defecto para comparación
file_comparison_default_comparison_path: "D:\\Mis Documentos"

# Grupos de servidores
file_comparison_source_group: "servers_produccion"
file_comparison_target_group: "servers_contingencia"
